# -*- coding: utf-8 -*-
"""Oquecomprar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bowRJfU7UBUQQhCG7Io8o_4kRspK2-x9
"""

frutas = ["Maça", "Banana", "Pera", "Uva"]
guloseimas = ["Bolacha", "Batata", "Fini", "Chocolate"]
comidas = ["Arroz", "Feijao", "Carne"]
bebidas = ["Refrigerante", "Suco de Laranja", "Agua"]

categorias = ["Frutas", "Guloseimas", "Comidas", "Bebidas"]
compras = [frutas, guloseimas, comidas, bebidas]

for indice, categoria in enumerate(categorias):
    print("Voce precisa comprar", len(compras[indice]), categoria+":")
    for compra in compras[indice]:
       print("-", compra)

